#make xclbin
KERNEL_NAME = kernel

TF_SOURCE_DIR = /home/luoxh/tensorflow
TF_LIB_DIR = /home/luoxh/Desktop/resnet/c++/lib

OCL_KERNEL_SRC = kernel.cpp
OCL_KERNEL_H = kernel.h

OCL_KERNEL_ARGS = --max_memory_ports all

include ./harness/harness.mk
